(() => {
  const s=(category,title,subtitle,content)=>({category,title,subtitle,content});
  const rows=items=>`<div class="concept-list">${items.map(([a,b])=>`<div class="concept-row"><strong>${a}</strong><p>${b}</p></div>`).join("")}</div>`;
  window.SLIDE_DECKS["ciencia-de-dados/correcao-p1"]={title:"Correção comentada da P1",slides:[
    s("Avaliação P1","Ciência de Dados","Revisão dos conceitos cobrados na P1",`<div class="hero-story"><div class="hero-emoji">📊</div><div><h2>Decidir com métricas corretas</h2><p>A prova conecta estatística descritiva, avaliação de classificadores, testes de hipótese e séries temporais.</p></div></div><div class="exam-warning exam-note"><strong>Q10 anulada em todas as versões.</strong> O conceito foi mantido somente para aprendizagem e não deve gerar pontuação.</div>`),
    s("Processo e dados","CRISP-DM e tipos de variáveis","A pergunta de negócio orienta a técnica",rows([["Avaliação","Na fase 5 do CRISP-DM, verifique se o modelo atende às metas do negócio antes da implantação."],["Nominal","Categorias sem ordem, como identificadores e códigos."],["Ordinal","Categorias ordenadas, como severidade baixa, média e alta."],["Discreta","Contagens inteiras, como número de falhas."],["Contínua","Medições em escala, como temperatura e pressão."]]) ),
    s("Classificação","Classe rara e custos assimétricos","Acurácia alta pode esconder um modelo inútil",`<div class="grid-2"><div class="formula-box">Acurácia = (VP + VN) / total<br>Recall = VP / (VP + FN)<br>Precisão = VP / (VP + FP)</div><div>${rows([["Falso negativo","Uma peça defeituosa é liberada. Pode provocar acidentes, recall e prejuízo."],["Falso positivo","Uma peça boa é reprovada. Normalmente gera reinspeção e custo operacional."]])}</div></div><div class="exam-warning exam-note">Se apenas 0,1% das peças têm defeito, prever tudo como bom produz 99,9% de acurácia e 0% de recall.</div>`),
    s("Métricas","Recall, precisão, acurácia e F1","Cada métrica responde a uma pergunta",rows([["Recall","Entre os positivos reais, quantos o modelo encontrou? Priorize quando falso negativo custa mais."],["Precisão","Entre as previsões positivas, quantas estavam corretas? Importa quando falsos alarmes custam caro."],["Acurácia","Qual fração total foi classificada corretamente? Cuidado com classes desbalanceadas."],["F1","Média harmônica entre precisão e recall. Penaliza desequilíbrio entre as duas métricas."]])+`<div class="formula-box">F1 = 2 × (Precisão × Recall) / (Precisão + Recall)</div>`),
    s("Estatística robusta","Mediana, IQR e regra de Tukey","Valores extremos afetam medidas de maneiras diferentes",`<div class="grid-2"><div>${rows([["Mediana","Depende da posição central dos dados ordenados e resiste melhor a extremos."],["IQR","Q3 - Q1 descreve os 50% centrais dos dados."],["Média e desvio","Usam magnitudes e são deslocados por valores extremos, especialmente pelos desvios quadráticos."]])}</div><div><div class="formula-box">IQR = Q3 - Q1<br>Limite superior = Q3 + 1,5 × IQR</div><p class="mini-note">A: 90 °C. B: 80 °C. C: 125 bar. D: 75 mm. Um outlier superior fica estritamente acima do limite.</p></div></div>`),
    s("Inferência","Shapiro-Wilk e p-valor","A decisão é sobre rejeitar ou não H0",`<div class="formula-box">Se p &lt; α: rejeitar H0 de normalidade<br>Se p ≥ α: não rejeitar H0</div>${rows([["Versão A","0,018 < 0,05: rejeitar normalidade."],["Versão B","0,082 > 0,05: não rejeitar H0."],["Versão C","0,004 < 0,01: rejeitar normalidade."],["Versão D","0,125 > 0,05: não rejeitar H0."]])}<div class="exam-warning exam-note">Não rejeitar H0 não prova que os dados são normais. Significa que o teste não encontrou evidência suficiente contra a normalidade.</div>`),
    s("Séries temporais","Tendência, sazonalidade e ruído","A decomposição separa estruturas com comportamentos distintos",rows([["Tendência","Mudança de longo prazo no nível da série."],["Sazonalidade","Padrão que se repete em intervalos regulares."],["Ruído ou resíduo","Flutuação aleatória que permanece após explicar as estruturas principais."]]) ),
    s("Questão anulada","Paradigmas de aprendizado","Conteúdo mantido apenas para estudo",rows([["Regressão linear","Aprendizado supervisionado com saída numérica contínua."],["Árvore de classificação","Aprendizado supervisionado com saída em classes."],["K-Means","Aprendizado não supervisionado para agrupamento."],["PCA","Método não supervisionado para redução dimensional."]])+`<div class="exam-warning exam-note"><strong>Motivo da anulação:</strong> a cobertura desses paradigmas antes da P1 era parcial. O conteúdo permanece como ampliação conceitual.</div>`),
    s("Discursiva Q11","Matriz de confusão e custo do erro","Cada item vale 0,90",`<div class="grid-2"><div><h2>Item A</h2><p>Defina FP como reprovar uma peça boa e FN como liberar uma peça defeituosa. Explique por que FN tende a ser mais grave no cenário industrial.</p></div><div><h2>Item B</h2><p>Mostre por que a acurácia é dominada pela classe majoritária. Cite recall, precisão, F1 e o custo dos erros como complementos.</p></div></div><div class="exam-note">A resposta precisa interpretar o cenário. Escrever apenas as fórmulas não explica o risco operacional.</div>`),
    s("Discursiva Q12","Robustez e decisão sobre normalidade","Cada item vale 0,90",`<div class="grid-2"><div><h2>Item A</h2><p>Compare mediana e IQR com média e desvio padrão. Robustez significa menor sensibilidade, não imunidade absoluta.</p></div><div><h2>Item B</h2><p>Explique a regra de decisão pelo p-valor e como ela orienta pressupostos, transformações ou métodos robustos e não paramétricos.</p></div></div>`),
    s("Raciocínio estatístico","Por que essas justificativas estão corretas","A métrica precisa representar o risco da decisão",rows([["Classe rara","A classe majoritária domina a acurácia. Por isso um modelo pode acertar quase tudo e ainda ignorar todos os defeitos."],["Recall","O denominador contém todos os positivos reais. A métrica responde quantos defeitos escaparam da detecção."],["Mediana e IQR","Usam posições na ordenação, não a magnitude de todos os valores. Um extremo desloca menos essas medidas."],["Shapiro-Wilk","O p-valor mede compatibilidade com H0. Um valor alto significa evidência insuficiente para rejeitar, não prova de normalidade."],["CRISP-DM","Um modelo tecnicamente bom só tem valor se atender ao objetivo e ao custo de erro definidos pelo negócio."]]) ),
    s("Referência","Dicionário de siglas","Termos usados na prova e na correção",`<div class="grid-2"><div>${rows([["CRISP-DM","Cross-Industry Standard Process for Data Mining"],["EDA","Exploratory Data Analysis, análise exploratória de dados"],["VP","Verdadeiro positivo"],["VN","Verdadeiro negativo"],["FP","Falso positivo"],["FN","Falso negativo"]])}</div><div>${rows([["IQR","Interquartile Range, intervalo interquartil"],["H0","Hipótese nula"],["F1","Média harmônica entre precisão e recall"],["PCA","Principal Component Analysis"],["ML","Machine Learning, aprendizado de máquina"],["K-Means","Algoritmo de agrupamento por centroides"]])}</div></div>`),
    s("Síntese","Erros que reduzem a pontuação","Frases que precisam de correção",`<div class="mistake-list"><div><strong>Acurácia alta garante bom modelo</strong><p>Em classe rara, o recall pode ser zero.</p></div><div><strong>p alto prova normalidade</strong><p>O teste apenas não rejeita H0.</p></div><div><strong>Todo valor no limite é outlier</strong><p>A regra superior usa valor estritamente maior.</p></div><div><strong>Robusto significa imune</strong><p>Mediana e IQR ainda podem mudar.</p></div></div>`),
    s("Fechamento","Mapa de revisão","Quatro perguntas para escolher a ferramenta",`<div class="takeaway-list"><div><span>1</span><p>Qual é a <strong>meta de negócio</strong>?</p></div><div><span>2</span><p>Qual erro tem <strong>maior custo</strong>?</p></div><div><span>3</span><p>Os dados têm <strong>extremos ou desbalanceamento</strong>?</p></div><div><span>4</span><p>Qual conclusão o <strong>teste estatístico</strong> permite?</p></div></div>`)
  ]};
})();
