version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"   # UI do NameNode
      - "9000:9000"   # Porta HDFS
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    restart: always
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"   # UI do Spark Master
      - "7077:7077"   # Porta do Spark
    volumes:
      - ./spark/app:/opt/spark/app
    depends_on:
      - namenode
    networks:
      - hadoop

  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: spark-worker
    restart: always
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./spark/app:/opt/spark/app
    depends_on:
      - spark-master
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop:
