(() => {
  const s=(category,title,subtitle,content)=>({category,title,subtitle,content});
  const rows=items=>`<div class="concept-list">${items.map(([a,b])=>`<div class="concept-row"><strong>${a}</strong><p>${b}</p></div>`).join("")}</div>`;
  window.SLIDE_DECKS["devops/correcao-p1"]={title:"Correção comentada da P1",slides:[
    s("Avaliação P1","DevOps","Revisão dos conceitos cobrados na P1",`<div class="hero-story"><div class="hero-emoji">♾️</div><div><h2>Fluxo, qualidade e entrega contínua</h2><p>A avaliação conecta conceitos sobre CALMS, Git, testes, feedback e automação de entrega.</p></div></div><div class="exam-note">A correção enfatiza decisões de engenharia, não apenas os nomes das práticas.</div>`),
    s("Cultura e fluxo","CALMS e a Segunda Maneira","DevOps combina comportamento, automação e medição",rows([["Culture","Colaboração, responsabilidade compartilhada e análise sem culpabilização."],["Automation","Esteiras reduzem execução manual e tornam o processo repetível."],["Lean","Pequenos lotes, menos trabalho em progresso e eliminação de desperdício melhoram o fluxo."],["Measurement","Indicadores mostram qualidade, velocidade e confiabilidade."],["Sharing","Conhecimento e aprendizado circulam entre as equipes."],["Feedback","A Segunda Maneira devolve rapidamente ao desenvolvedor o resultado de testes e operação."]]) ),
    s("Versionamento","GitFlow e correções emergenciais","Cada branch possui uma função explícita",rows([["main","Mantém versões estáveis e publicadas."],["develop","Integra o trabalho destinado ao próximo lançamento."],["feature","Parte de develop e retorna a develop após revisão."],["release","Estabiliza uma versão e retorna a main e develop."],["hotfix","Parte de main para corrigir produção e retorna a main e develop."]])+`<div class="exam-warning exam-note">Branches isoladas por muito tempo acumulam divergências e produzem Merge Hell: conflitos e incompatibilidades aparecem tarde.</div>`),
    s("Integração contínua","Trunk-Based e Feature Flags","Mudanças pequenas reduzem o risco de integração",rows([["Trunk-Based","Integra alterações pequenas e frequentes em um tronco comum. Branches têm vida curta."],["Feature Flag","Mantém uma funcionalidade implantada, porém desativada para usuários, permitindo liberação controlada."],["Limite das flags","Elas reduzem exposição, mas não substituem CI, testes e revisão e não garantem ausência de regressões."]]) ),
    s("Entrega contínua","Delivery e Deployment","A diferença está na decisão final de produção",`<div class="grid-2"><div class="card"><h2>Continuous Delivery</h2><p>Build, testes e preparação são automatizados. O software fica pronto, mas uma pessoa autoriza ou dispara a implantação final.</p></div><div class="card"><h2>Continuous Deployment</h2><p>A própria esteira implanta após todos os critérios serem satisfeitos, sem aprovação humana por alteração.</p></div></div><div class="exam-note">Deployment descreve a implantação. Release descreve a exposição da funcionalidade aos usuários.</div>`),
    s("Qualidade","Pirâmide de testes","A base ampla oferece feedback rápido e localizado",rows([["Unitários","Testam lógica isolada, executam rápido e apontam a origem da falha com precisão."],["Integração","Verificam comunicação entre componentes, banco, filas ou serviços."],["E2E","Percorrem jornadas completas. São valiosos, porém mais lentos e frágeis."],["Pirâmide","Muitos unitários, menos integração e poucos E2E equilibram confiança e custo."]]) ),
    s("Qualidade antecipada","Shift-Left e Quality Gates","Detectar cedo reduz retrabalho",rows([["Shift-Left","Move testes, análise e segurança para etapas anteriores do fluxo."],["Quality Gate","Bloqueia o avanço quando testes, cobertura ou requisitos de segurança não atendem aos critérios."],["Proteção de branch","Exige pull request, revisão e checks obrigatórios e restringe alterações diretas na branch principal."]]) ),
    s("Discursiva Q11","GitFlow, Merge Hell e Trunk-Based","Cada item vale 0,90",`<div class="grid-2"><div><h2>Item A</h2><p>Explique main, develop, feature, release e hotfix. Relacione branches longas ao acúmulo de conflitos e incompatibilidades.</p></div><div><h2>Item B</h2><p>Descreva integração diária em tronco comum e branches curtas. Explique como Feature Flags separam implantação de liberação.</p></div></div><div class="exam-warning exam-note">Aceite a ressalva correta: Feature Flags reduzem exposição, mas não eliminam regressões.</div>`),
    s("Discursiva Q12","Decisão de implantação e duplos de teste","Cada item vale 0,90",`<div class="grid-2"><div><h2>Item A</h2><p>Compare aprovação humana no Continuous Delivery com implantação automática no Continuous Deployment.</p></div><div><h2>Item B</h2><p>Stubs fornecem respostas controladas. Mocks também verificam interações. Ambos isolam rede, banco e APIs em testes unitários.</p></div></div><div class="exam-note">Mocks e stubs não são obrigatórios quando o código já é puro e isolado. A integração real deve ser verificada em testes de integração.</div>`),
    s("Cobertura do material","Ressalvas do gabarito","A origem de alguns conceitos precisa ficar transparente",rows([["Segunda Maneira","O guia atribui o conceito à Semana 01. A aplicação de feedback automatizado aparece na Semana 07."],["Trunk-Based e flags","O guia os associa às Semanas 02 e 03, mas a cobertura explícita não foi localizada nos notebooks."],["Delivery × Deployment","A distinção aparece no guia da Semana 04. A Semana 03 traz exemplo de deployment."]]) ),
    s("Raciocínio de fluxo","Por que essas justificativas estão corretas","Feedback rápido reduz o tamanho e o custo do problema",rows([["Lotes pequenos","Poucas alterações por integração reduzem o espaço de busca quando algo falha e diminuem conflitos de merge."],["Pirâmide de testes","Testes unitários custam menos e isolam causas. E2E cobrem a jornada, mas são lentos e mais sensíveis ao ambiente."],["Shift-Left","Encontrar defeitos antes evita que código incorreto atravesse outras etapas e acumule retrabalho."],["Quality Gate","Critérios automatizados impedem que pressão ou distração transformem uma falha conhecida em implantação."],["Feature Flags","Separar implantação de liberação limita exposição, mas o código implantado ainda precisa de testes e observabilidade."]]) ),
    s("Referência","Dicionário de siglas","Termos usados na prova e na correção",`<div class="grid-2"><div>${rows([["CALMS","Culture, Automation, Lean, Measurement e Sharing"],["CI","Continuous Integration"],["CD","Continuous Delivery ou Continuous Deployment, conforme o contexto"],["WIP","Work in Progress"],["PR","Pull Request"]])}</div><div>${rows([["E2E","End to End"],["API","Application Programming Interface"],["UI","User Interface"],["QA","Quality Assurance"],["SLA","Service Level Agreement"]])}</div></div><div class="exam-warning exam-note">A sigla CD é ambígua. Sempre deixe claro se significa Delivery ou Deployment.</div>`),
    s("Síntese","Erros que reduzem a pontuação","Conceitos próximos não são equivalentes",`<div class="mistake-list"><div><strong>Delivery = Deployment</strong><p>Delivery mantém decisão humana final. Deployment automatiza a implantação.</p></div><div><strong>Mais E2E é sempre melhor</strong><p>A pirâmide prioriza testes rápidos na base.</p></div><div><strong>Feature Flag substitui testes</strong><p>Flags controlam exposição, não qualidade.</p></div><div><strong>Mock é obrigatório</strong><p>Código já isolado pode ser testado sem duplos.</p></div></div>`),
    s("Fechamento","Mapa de revisão","O fluxo precisa produzir feedback e confiança",`<div class="takeaway-list"><div><span>1</span><p><strong>Lotes pequenos</strong> facilitam integração.</p></div><div><span>2</span><p><strong>Testes antecipados</strong> reduzem retrabalho.</p></div><div><span>3</span><p><strong>Gates</strong> transformam critérios em bloqueios objetivos.</p></div><div><span>4</span><p><strong>Automação</strong> preserva repetibilidade.</p></div></div>`)
  ]};
})();
