(() => {
  const s = (category, title, subtitle, content, extra = "") => ({ category, title, subtitle, content, extra });
  const rows = items => `<div class="concept-list">${items.map(([a,b]) => `<div class="concept-row"><strong>${a}</strong><p>${b}</p></div>`).join("")}</div>`;
  window.SLIDE_DECKS["automacao-industrial/correcao-p1"] = {
    title: "Correção comentada da P1",
    slides: [
      s("Avaliação P1", "Automação Industrial", "Revisão dos conceitos cobrados na P1", `<div class="hero-story"><div class="hero-emoji">🏭</div><div><h2>Conceitos com fundamento técnico</h2><p>A revisão está organizada pelos conceitos cobrados. Cada justificativa parte do mecanismo técnico e mostra sua consequência no processo.</p></div></div>`),
      s("ISA-95 e TA", "Controle crítico permanece no nível 1", "Disponibilidade e determinismo orientam a arquitetura", rows([["Nível 1","CLPs e controladores executam controle básico e intertravamentos."],["Nível 2","Supervisão e operação acompanham o processo."],["Nível 3","MES e gestão da produção tratam operações e OEE."],["Nível 4","ERP cuida do planejamento empresarial."]])+`<div class="exam-warning exam-note"><strong>Regra central:</strong> nuvem, MES ou ERP podem consumir dados, mas não devem ser dependência de uma parada crítica. Latência variável e perda de enlace comprometem a segurança.</div>`),
      s("Instrumentação", "Sinais 4-20 mA e PWM", "Diagnóstico no zero vivo e controle pelo duty cycle", `<div class="grid-2"><div><div class="formula-box">Percentual = (I - 4 mA) / 16 mA<br>12 mA = 50%<br>16 mA = 75%</div><p class="mini-note">Em uma escala de 0 a 10 bar, 16 mA representa 7,5 bar.</p></div><div>${rows([["Zero vivo","4 mA representa o menor valor válido. Leitura próxima de 0 mA sugere cabo rompido, falta de alimentação ou mau contato."],["PWM","Duty cycle é a fração ativa do período. Mantendo amplitude e frequência, maior duty cycle produz maior valor médio e potência."]])}</div></div>`),
      s("Sensores e acionamentos", "Escolha pelo princípio físico", "Material, distância e ambiente mudam a resposta", rows([["Indutivo","Detecta metal condutor por campo eletromagnético. É a escolha natural para engrenagens metálicas."],["Capacitivo","Detecta materiais metálicos e não metálicos pela alteração de capacitância. Exige ajuste e pode sofrer influência do ambiente."],["Fotoelétrico","Usa luz. Cor, transparência e sujeira podem afetar a detecção."],["Ultrassônico","Mede tempo de voo do eco. Pode medir nível sem contato, mas espuma, vapor e geometria interferem."],["Servo","Encoder ou resolver fecha a malha e permite corrigir continuamente o erro de posição."]]) ),
      s("CLP", "Ciclo de scan e imagem de processo", "A lógica usa uma fotografia estável das entradas", `<div class="sequence"><span>1. Ler entradas</span><span>2. Executar lógica</span><span>3. Atualizar saídas</span></div>${rows([["PII","As entradas físicas são copiadas para a memória imagem no início do ciclo."],["Execução","O programa calcula estados internos e a imagem de saídas usando os valores capturados."],["PIO","As saídas físicas recebem os novos estados ao final da varredura."],["Determinismo","Significa conhecer um limite temporal de resposta. Não significa apenas executar rapidamente."]])}`),
      s("MQTT", "Tópicos e curingas", "A hierarquia permite selecionar exatamente o fluxo necessário", `<div class="formula-box">fabrica/linha2/+/energia/corrente<br>planta/linha3/+/sensores/vibracao</div>${rows([["Curinga +","Substitui exatamente um nível. Nos exemplos, recebe a grandeza de todas as máquinas da linha indicada."],["Broker","Recebe publicações e distribui mensagens aos assinantes interessados."],["Publish/subscribe","Evita consultas repetitivas e desacopla produtores de consumidores."]])}`),
      s("MQTT e borda", "Entrega, estado e disponibilidade", "Cada recurso resolve um problema diferente", rows([["QoS 1","Entrega ao menos uma vez e pode duplicar mensagens. É adequado quando a aplicação descarta duplicatas de forma idempotente."],["QoS 2","Entrega exatamente uma vez com handshake maior. Use quando a duplicação for inaceitável e o custo adicional fizer sentido."],["Retain","O broker guarda o último valor e o entrega imediatamente a um novo assinante."],["LWT","O broker publica uma mensagem definida quando detecta desconexão inesperada do cliente."],["Edge computing","Filtra, agrega e detecta limites localmente. Reduz latência e tráfego e continua operando durante instabilidade externa."]]) ),
      s("Discursivas", "Ciclo de scan e arquitetura IIoT", "Como os conceitos se conectam", `<div class="grid-2"><div><h2>Ciclo de scan</h2><div class="rubric-list"><div class="rubric-item"><span>Leitura das entradas para PII</span><b>0,45</b></div><div class="rubric-item"><span>Lógica usa a imagem</span><b>0,35</b></div><div class="rubric-item"><span>Atualização da PIO</span><b>0,35</b></div><div class="rubric-item"><span>Latência e determinismo</span><b>0,65</b></div></div></div><div><h2>Arquitetura IIoT</h2><div class="rubric-list"><div class="rubric-item"><span>Sensor, CLP, edge, broker e assinante</span><b>0,45</b></div><div class="rubric-item"><span>Controle crítico local</span><b>0,45</b></div><div class="rubric-item"><span>Tópicos coerentes</span><b>0,30</b></div><div class="rubric-item"><span>QoS 1, retain e LWT</span><b>0,60</b></div></div></div></div>`),
      s("Discursivas", "Instrumentação e sinais", "Princípio físico e consequência prática", `<div class="grid-2"><div><h2>Seleção de sensores</h2><p>Compare o princípio, os materiais detectáveis e os limites ambientais. Justifique o indutivo para metal e uma solução sem contato para nível.</p></div><div><h2>4-20 mA e PWM</h2><p>Explique zero vivo, diagnóstico próximo de 0 mA, robustez frente a 0-10 V e a relação entre período, tempo ativo, duty cycle e valor médio.</p></div></div><div class="exam-note">Uma boa resposta conecta o princípio físico ao cenário. Apenas listar nomes de sensores ou sinais não atende aos critérios.</div>`),
      s("Discursivas", "ISA-95 e MQTT", "Arquitetura e comunicação industrial", `<div class="grid-2"><div><h2>ISA-95</h2><p>Relacione níveis 1 a 4, destaque determinismo e disponibilidade da TA e explique por que o intertravamento fica no controlador local.</p></div><div><h2>MQTT versus polling</h2><p>Compare consulta contínua com publish/subscribe, explique o broker, os tópicos hierárquicos e quando usar retain e LWT.</p></div></div>`),
      s("Raciocínio técnico", "Por que essas justificativas estão corretas", "O mecanismo físico ou lógico determina a consequência", rows([["Controle local","Intertravamentos dependem de tempo previsível. Colocar rede, nuvem ou ERP no caminho acrescenta latência variável e novos pontos de falha."],["4-20 mA","A corrente circula pelo mesmo loop e sofre menos influência da resistência do cabo. O zero vivo reserva 0 mA para diagnóstico de falha."],["Scan do CLP","A imagem de entradas evita que valores mudem no meio da execução e produz uma decisão coerente durante cada ciclo."],["MQTT","Publish/subscribe desacopla produtores e consumidores. QoS, retain e LWT tratam problemas diferentes: entrega, estado inicial e ausência inesperada."],["Edge","Processar perto da máquina reduz o caminho de comunicação e permite resposta local quando o enlace externo oscila."]]) ),
      s("Referência", "Dicionário de siglas", "Termos usados na prova e na correção", `<div class="grid-2"><div>${rows([["CLP","Controlador Lógico Programável"],["PII","Process Image Input, imagem de entradas"],["PIO","Process Image Output, imagem de saídas"],["TA","Tecnologia da Automação"],["TI","Tecnologia da Informação"],["ISA-95","Norma de integração entre controle e sistemas empresariais"],["IIoT","Internet Industrial das Coisas"]])}</div><div>${rows([["MQTT","Message Queuing Telemetry Transport"],["QoS","Quality of Service, nível de garantia de entrega"],["LWT","Last Will and Testament"],["PWM","Pulse Width Modulation"],["MES","Manufacturing Execution System"],["ERP","Enterprise Resource Planning"],["OEE","Overall Equipment Effectiveness"]])}</div></div>`),
      s("Síntese", "Erros que reduzem a pontuação", "Distinções que precisam aparecer na resposta", `<div class="mistake-list"><div><strong>Rápido = determinístico</strong><p>Determinismo exige limite temporal conhecido.</p></div><div><strong>0 mA = zero do processo</strong><p>No loop 4-20 mA, 0 mA sugere falha.</p></div><div><strong>QoS 1 elimina duplicatas</strong><p>Ele permite duplicatas. A aplicação deve ser idempotente.</p></div><div><strong>Retain e LWT são iguais</strong><p>Retain guarda estado. LWT comunica queda inesperada.</p></div></div>`),
      s("Fechamento", "Mapa de revisão", "Os conceitos que conectam as quatro versões", `<div class="takeaway-list"><div><span>1</span><p><strong>Controle local</strong> sustenta segurança e determinismo.</p></div><div><span>2</span><p><strong>Instrumentação</strong> exige interpretar sinal e ambiente.</p></div><div><span>3</span><p><strong>MQTT</strong> separa comunicação, entrega e estado.</p></div><div><span>4</span><p><strong>Edge</strong> aproxima análise do processo.</p></div></div>`)
    ]
  };
})();
