(() => {
  const s=(category,title,subtitle,content)=>({category,title,subtitle,content});
  const rows=items=>`<div class="concept-list">${items.map(([a,b])=>`<div class="concept-row"><strong>${a}</strong><p>${b}</p></div>`).join("")}</div>`;
  window.SLIDE_DECKS["computacao-em-nuvem/correcao-p1"]={title:"Correção comentada da P1",slides:[
    s("Avaliação P1","Computação em Nuvem","Revisão dos conceitos cobrados na P1",`<div class="hero-story"><div class="hero-emoji">☁️</div><div><h2>Arquitetura, segurança e responsabilidade</h2><p>A avaliação exige compreender decisões de serviço, identidade, armazenamento, redes e alta disponibilidade.</p></div></div><div class="exam-note">Cada justificativa relaciona uma decisão arquitetural ao risco que ela controla.</div>`),
    s("Modelos de serviço","Responsabilidade compartilhada","O serviço contratado desloca a fronteira de gestão",rows([["IaaS","O provedor gerencia infraestrutura e hypervisor. O cliente gerencia SO convidado, identidades, dados, aplicações e configurações de rede."],["PaaS","O provedor também gerencia SO e runtime. O cliente permanece responsável pela aplicação e pelos dados."],["SaaS","O provedor opera quase toda a pilha. O cliente ainda administra usuários, acessos, dados e configuração de uso."],["Regra AWS","A AWS protege a segurança da nuvem. O cliente protege o que coloca e configura na nuvem."]]) ),
    s("IAM","Menor privilégio e credenciais temporárias","Permissão deve limitar ação, recurso e duração",rows([["Policy","Define quais ações são permitidas ou negadas e sobre quais recursos."],["Deny explícito","Prevalece sobre qualquer Allow aplicável."],["Role","Fornece credenciais temporárias e evita distribuir chaves estáticas."],["Menor privilégio","Concede somente o necessário para a tarefa e reduz o impacto de vazamentos."]])+`<div class="exam-warning exam-note">Chaves estáticas ampliam o tempo de exposição. Roles permitem expiração, rotação e escopo controlado.</div>`),
    s("Disponibilidade","Remover pontos únicos de falha","Todas as camadas críticas precisam sobreviver à falha de uma AZ",`<div class="sequence"><span>Balanceador</span><span>Computação em múltiplas AZs</span><span>Banco Multi-AZ</span></div>${rows([["Banco em AZ única","Continua sendo ponto único de falha mesmo quando as instâncias de aplicação são redundantes."],["Health checks","Retiram alvos com falha e direcionam tráfego aos saudáveis."],["Backup e recuperação","Redundância não substitui cópias e procedimentos testados de restauração."],["Elasticidade","Ajusta capacidade conforme demanda. É diferente de alta disponibilidade, embora possa colaborar com ela."]])}`),
    s("Armazenamento","EBS, EFS e S3 resolvem necessidades diferentes","Escolha pelo modo de acesso e pelo ciclo de vida do dado",rows([["EBS","Armazenamento em bloco para uso ativo por instâncias. Comporta sistemas de arquivos e volumes de banco."],["EFS","Sistema de arquivos gerenciado e compartilhável por várias instâncias, com desenho multi-AZ."],["S3","Armazenamento de objetos durável para arquivos, artefatos e backups. Não funciona como volume de bloco tradicional."]]) ),
    s("Containers","Kernel compartilhado reduz sobrecarga","Container não virtualiza um sistema operacional completo",`<div class="grid-2"><div>${rows([["Container","Compartilha o kernel do host, inicia rapidamente e consome menos memória."],["Máquina virtual","Inclui sistema operacional convidado e oferece isolamento por virtualização de hardware."]])}</div><div class="formula-box">Imagem + configuração<br>↓<br>Container em execução<br>↓<br>Serviço acessível pela rede</div></div>`),
    s("Rede de aplicações","Exposição seletiva e DNS interno","Somente a borda precisa ficar pública",rows([["Serviço de borda","API, proxy ou frontend pode publicar a porta necessária."],["Banco de dados","Permanece em rede interna e recebe tráfego apenas dos componentes autorizados."],["Security Group","É stateful. O retorno de uma conexão permitida é liberado automaticamente."],["Docker Compose","Serviços na mesma rede resolvem uns aos outros pelo nome usando DNS interno."]]) ),
    s("Discursivas","Responsabilidade compartilhada e alta disponibilidade","Fundamentos de arquitetura resiliente",`<div class="grid-2"><div><h2>Responsabilidade</h2><div class="rubric-list"><div class="rubric-item"><span>Segurança da nuvem × na nuvem</span><b>0,50</b></div><div class="rubric-item"><span>Infraestrutura e hypervisor: AWS</span><b>0,30</b></div><div class="rubric-item"><span>SO, SG, credenciais e dados: cliente</span><b>0,60</b></div><div class="rubric-item"><span>Variação entre IaaS e SaaS</span><b>0,40</b></div></div></div><div><h2>Alta disponibilidade</h2><div class="rubric-list"><div class="rubric-item"><span>Banco de AZ única é ponto de falha</span><b>0,40</b></div><div class="rubric-item"><span>Dados redundantes ou Multi-AZ</span><b>0,55</b></div><div class="rubric-item"><span>Computação distribuída e balanceamento</span><b>0,40</b></div><div class="rubric-item"><span>Health checks, backup e recuperação</span><b>0,45</b></div></div></div></div>`),
    s("Discursivas","IAM, armazenamento e containers","Fundamentos de segurança e persistência",`<div class="grid-2"><div><h2>IAM e credenciais</h2><p>Defina menor privilégio, explique a precedência de Deny e compare roles temporárias com chaves estáticas em risco, escopo e resposta a vazamento.</p></div><div><h2>Armazenamento e containers</h2><p>Associe EBS, EFS e S3 aos casos corretos. Explique rede privada, DNS interno e exposição somente do serviço de borda.</p></div></div><div class="exam-note">A justificativa deve mencionar o padrão de acesso ao dado. Dizer apenas que um serviço “é melhor” não demonstra a escolha arquitetural.</div>`),
    s("Raciocínio arquitetural","Por que essas justificativas estão corretas","Cada escolha responde a um tipo de risco ou acesso",rows([["Responsabilidade","Quanto mais gerenciado o serviço, mais camadas o provedor opera. O cliente nunca deixa de responder por identidades, configuração e dados."],["Deny explícito","A negação prevalece para criar um limite de segurança que permissões amplas não conseguem contornar acidentalmente."],["Multi-AZ","Réplicas na mesma zona compartilham a mesma falha física. Distribuir zonas reduz falhas correlacionadas."],["EBS, EFS e S3","Bloco, arquivo e objeto possuem interfaces diferentes. A aplicação precisa do serviço cujo modo de acesso corresponde ao dado."],["Rede privada","Não publicar o banco reduz a superfície de ataque. Somente o componente de borda precisa receber tráfego externo."]]) ),
    s("Referência","Dicionário de siglas","Termos usados na prova e na correção",`<div class="grid-2"><div>${rows([["IaaS","Infrastructure as a Service"],["PaaS","Platform as a Service"],["SaaS","Software as a Service"],["IAM","Identity and Access Management"],["AWS","Amazon Web Services"],["AZ","Availability Zone, zona de disponibilidade"]])}</div><div>${rows([["EBS","Elastic Block Store"],["EFS","Elastic File System"],["S3","Simple Storage Service"],["SG","Security Group"],["DNS","Domain Name System"],["SO","Sistema operacional"],["API","Application Programming Interface"]])}</div></div>`),
    s("Síntese","Erros que reduzem a pontuação","Distinções essenciais",`<div class="mistake-list"><div><strong>Allow sempre vence</strong><p>Deny explícito tem precedência.</p></div><div><strong>Redundância de aplicação basta</strong><p>O banco em uma AZ mantém o ponto único de falha.</p></div><div><strong>S3 substitui qualquer disco</strong><p>S3 armazena objetos, não blocos.</p></div><div><strong>Banco precisa ser público</strong><p>A aplicação acessa o banco pela rede privada.</p></div></div>`),
    s("Fechamento","Mapa de decisão","Quatro verificações antes de escolher um serviço",`<div class="takeaway-list"><div><span>1</span><p>Quem administra cada <strong>camada</strong>?</p></div><div><span>2</span><p>Qual é o menor <strong>privilégio</strong> necessário?</p></div><div><span>3</span><p>Onde existe um <strong>ponto de falha</strong>?</p></div><div><span>4</span><p>O dado exige bloco, arquivo ou <strong>objeto</strong>?</p></div></div>`)
  ]};
})();
