window.SLIDE_DECKS["computacao-em-nuvem/semana-10"] = {
  title: "Armazenamento em nuvem: bloco, objeto e arquivo",
  slides: [
    {category:"Semana 10",title:"Armazenamento em nuvem",subtitle:"Como escolher entre bloco, objeto e arquivo",content:`<div class="hero-story"><div class="hero-emoji">💾</div><div><h2>O dado pede um modelo de acesso</h2><p>A aplicação precisa de um disco, de uma API ou de um diretório compartilhado?</p></div></div>`},
    {category:"Contexto",title:"Armazenamento é uma camada da arquitetura",subtitle:"A aplicação precisa sobreviver a reinícios, falhas e crescimento",content:`<div class="image-card"><img src="../Aulas/images/semana_10_fluxo_vpc_publica.png" alt="Fluxo de uma aplicação em uma VPC pública"><p>O diagrama mostra o contexto de infraestrutura em que os dados persistentes são usados pela aplicação.</p></div>`},
    {category:"Comparação",title:"Três modelos, três perguntas",subtitle:"A unidade de acesso define a escolha",content:`<table class="answer-table"><thead><tr><th>Modelo</th><th>Unidade</th><th>Pergunta</th><th>AWS</th></tr></thead><tbody><tr><td><strong>Bloco</strong></td><td>volume/dispositivo</td><td>Preciso de semântica de disco?</td><td>EBS</td></tr><tr><td><strong>Objeto</strong></td><td>objeto + chave</td><td>Consigo acessar por API?</td><td>S3</td></tr><tr><td><strong>Arquivo</strong></td><td>arquivos/diretórios</td><td>Preciso montar e compartilhar?</td><td>EFS</td></tr></tbody></table>`},
    {category:"Bloco",title:"EBS: o disco da máquina",subtitle:"Baixa latência e semântica de sistema de arquivos",content:`<div class="concept-list"><div class="concept-row"><strong>Use para</strong><p>Sistema operacional, banco de dados e workloads com escrita frequente.</p></div><div class="concept-row"><strong>Como aparece</strong><p>Um dispositivo como <code>/dev/xvdf</code>, que pode ser formatado e montado.</p></div><div class="concept-row"><strong>Cuidado</strong><p>Persistência não é backup; alta disponibilidade exige snapshots ou replicação.</p></div></div>`},
    {category:"Objeto",title:"S3: dados acessados por API",subtitle:"Conteúdo, metadados e chave dentro de um bucket",content:`<div class="grid-2"><div class="formula-box"><strong>chave</strong><br><code>clientes/42/avatar.png</code><br><br><strong>metadados</strong><br>tipo, classe, versão</div><div class="concept-list"><div class="concept-row"><strong>Use para</strong><p>Imagens, vídeos, documentos, backups, datasets e conteúdo estático.</p></div><div class="concept-row"><strong>Recursos</strong><p>Versionamento, ciclo de vida, eventos e classes de armazenamento.</p></div></div></div>`},
    {category:"Arquivo",title:"EFS: diretórios compartilhados",subtitle:"Um sistema de arquivos gerenciado para várias instâncias",content:`<div class="concept-list"><div class="concept-row"><strong>Use quando</strong><p>Várias instâncias Linux precisam acessar os mesmos uploads ou arquivos.</p></div><div class="concept-row"><strong>Interface</strong><p>A aplicação trabalha com caminhos, diretórios e permissões via montagem NFS.</p></div><div class="concept-row"><strong>Limite</strong><p>Compartilhamento não substitui banco de dados nem resolve concorrência automaticamente.</p></div></div>`},
    {category:"Decisão",title:"Mapa rápido de escolha",subtitle:"Comece pelo padrão de acesso",content:`<div class="sequence"><span>Banco de dados → BLOCO</span><span>Imagens e backups → OBJETO</span><span>Diretório comum → ARQUIVO</span></div><div class="exam-note">A regra é um ponto de partida: valide latência, throughput, compartilhamento, disponibilidade, segurança e custo.</div>`},
    {category:"Arquitetura",title:"Caso: aplicação web de produtos",subtitle:"Separando dados transacionais de arquivos",content:`<div class="concept-list"><div class="concept-row"><strong>Banco</strong><p>Serviço gerenciado ou volume de bloco para transações.</p></div><div class="concept-row"><strong>Imagens</strong><p>S3; o banco guarda apenas a chave do objeto.</p></div><div class="concept-row"><strong>Compartilhamento</strong><p>EFS somente se várias instâncias precisarem de diretório montado.</p></div><div class="concept-row"><strong>Proteção</strong><p>Backup automatizado, versionamento, retenção e IAM de menor privilégio.</p></div></div>`},
    {category:"Atividade",title:"Escolha o armazenamento",subtitle:"Justifique a decisão pelo acesso ao dado",content:`<div class="formula-box"><strong>Classifique:</strong> PostgreSQL transacional · catálogo de imagens · uploads compartilhados · backup mensal.</div><div class="concept-list"><div class="concept-row"><strong>Entregue</strong><p>Modelo escolhido, requisito de latência, estratégia de backup e risco de indisponibilidade.</p></div></div>`},
    {category:"Síntese",title:"O essencial para levar",subtitle:"Bloco, objeto e arquivo não são intercambiáveis",content:`<div class="hero-story"><div class="hero-emoji">🧭</div><div><h2>Escolha pelo modelo de acesso</h2><p><strong>Bloco</strong> para disco e banco · <strong>Objeto</strong> para conteúdo e backup · <strong>Arquivo</strong> para diretórios compartilhados.</p></div></div>`}
  ]
};
