window.SLIDE_DECKS["computacao-em-nuvem/semana-10"]={title:"Da EC2 pública à arquitetura de rede",slides:[
{category:"Semana 10",title:"Da EC2 pública à arquitetura de rede",subtitle:"Leitura da VPC existente e rastreamento do tráfego",content:`<div class="hero-story"><div class="hero-emoji">🌐</div><div><h2>Uma requisição atravessa várias camadas</h2><p>VPC, sub-rede, rotas, IP público, Security Group, SO e Docker precisam cooperar.</p></div></div>`},
{category:"Contexto",title:"O fluxo da VPC pública",subtitle:"Da Internet até a aplicação na EC2",content:`<div class="image-card"><img src="../Aulas/images/semana_10_fluxo_vpc_publica.png" alt="Fluxo de uma VPC pública"><p>O diagrama conecta Internet Gateway, sub-rede, Security Group, EC2 e rede Docker.</p></div>`},
{category:"Camadas",title:"Seis perguntas para localizar a falha",subtitle:"Não confunda rede, acesso e aplicação",content:`<div class="concept-list"><div class="concept-row"><strong>Endereçamento</strong><p>Qual é o CIDR e o IP do host?</p></div><div class="concept-row"><strong>Roteamento</strong><p>Existe rota local ou rota ao IGW?</p></div><div class="concept-row"><strong>Acesso</strong><p>O Security Group permite origem, protocolo e porta?</p></div><div class="concept-row"><strong>Publicação</strong><p>O SO e o Docker estão escutando e mapeando a porta?</p></div></div>`},
{category:"CIDR",title:"VPC, sub-rede e endereços",subtitle:"A sub-rede segmenta o espaço da VPC",content:`<div class="grid-2"><div class="formula-box">VPC <strong>10.0.0.0/16</strong><br>Sub-rede <strong>10.0.1.0/24</strong><br>Instância <strong>10.0.1.25</strong></div><div class="concept-list"><div class="concept-row"><strong>AWS reserva 5 IPs</strong><p>Em uma /24: 256 endereços matemáticos e estimativa de 251 utilizáveis.</p></div></div></div>`},
{category:"Roteamento",title:"Tabela de rotas e maior prefixo",subtitle:"A rota mais específica vence",content:`<table class="answer-table"><thead><tr><th>Destino</th><th>Alvo</th><th>Uso</th></tr></thead><tbody><tr><td><code>10.0.0.0/16</code></td><td><code>local</code></td><td>tráfego interno</td></tr><tr><td><code>0.0.0.0/0</code></td><td>Internet Gateway</td><td>Internet</td></tr></tbody></table><div class="exam-note">Para 10.0.2.10, a rota /16 vence a rota padrão /0.</div>`},
{category:"Sub-rede pública",title:"Rota pública não basta",subtitle:"Seis condições para alcançar a EC2",content:`<div class="sequence"><span>1. IGW anexado</span><span>2. Rota 0.0.0.0/0</span><span>3. IP público</span><span>4. Security Group</span><span>5. Serviço no SO</span><span>6. Binding Docker</span></div>`},
{category:"Firewall",title:"Security Group: estado e menor privilégio",subtitle:"Autorizar somente o necessário",content:`<div class="concept-list"><div class="concept-row"><strong>Stateful</strong><p>Respostas de conexões permitidas são aceitas automaticamente.</p></div><div class="concept-row"><strong>Exemplo</strong><p>SSH/22 para IP /32; HTTP/80 público; Node-RED/1880 apenas para rede institucional.</p></div></div>`},
{category:"Diagnóstico",title:"Sintoma → causa provável",subtitle:"Evidências orientam o próximo teste",content:`<table class="answer-table"><thead><tr><th>Sintoma</th><th>Hipótese</th><th>Teste</th></tr></thead><tbody><tr><td>Timeout</td><td>rota ou Security Group</td><td><code>nc -zvw3 IP PORTA</code></td></tr><tr><td>Refused</td><td>nada escuta</td><td><code>ss -lntp</code></td></tr><tr><td>Sem binding</td><td>Docker não publicou</td><td><code>docker ps</code></td></tr><tr><td>404</td><td>rota da aplicação ausente</td><td><code>curl -i</code></td></tr></tbody></table>`},
{category:"Multicloud",title:"Conceitos equivalentes",subtitle:"O vocabulário muda; o raciocínio permanece",content:`<table class="answer-table"><thead><tr><th>Conceito</th><th>AWS</th><th>Azure</th><th>GCP</th><th>Oracle</th></tr></thead><tbody><tr><td>Rede</td><td>VPC</td><td>VNet</td><td>VPC Network</td><td>VCN</td></tr><tr><td>Firewall</td><td>Security Group</td><td>NSG</td><td>VPC Firewall</td><td>Security List/NSG</td></tr><tr><td>Rotas</td><td>Route Table</td><td>UDR</td><td>Routes</td><td>Route Table</td></tr></tbody></table>`},
{category:"Atividade",title:"Investigue a arquitetura existente",subtitle:"Inventário da implantação da Semana 07",content:`<div class="formula-box"><strong>Entregue:</strong> CIDRs, rotas, IPs, regras do Security Group, portas Docker e caminho da requisição até Node-RED ou Flask.</div><div class="exam-note">Crie três falhas hipotéticas e indique a evidência que distingue cada camada.</div>`},
{category:"Síntese",title:"Siga o pacote, camada por camada",subtitle:"Acesso público é uma cadeia de decisões",content:`<div class="hero-story"><div class="hero-emoji">🧭</div><div><h2>VPC → rota → Security Group → SO → Docker → aplicação</h2><p>Uma falha em qualquer elo muda o sintoma e o teste adequado.</p></div></div>`}
]};
